### ISSUE TITLE
Prefer using MixPanel's reserved properties for the user

### ISSUE THREAD

**Issue by RomulusED69** [gordalina/GordalinaMixpanelBundle#15]
In the MixPanel documentation, they list some [reserved properties for the User profiles](https://help.mixpanel.com/hc/en-us/articles/115004708186-Profile-Properties): 
- `$first_name`
- `$last_name`
- `$email`
- `$phone` 
- .... 

This way, our users are _better_ integrated in MixPanel, see:
![Sélection_113](https://user-images.githubusercontent.com/9000452/93340500-29662c00-f82d-11ea-951b-1c1fc204c6e1.png)

**Comment by gordalina** [comment]
Thank you for submitting this issue and the PR that fixes it. I've issued `3.2.0`.
Let me know if you are interested in being maintainers of this package.
