### ISSUE TITLE
Stopwatch $stopwatch is required in Flusher __construct

### ISSUE THREAD

**Issue by kpotehin** [gordalina/GordalinaMixpanelBundle#2]
Flusher __construct() declares the 2nd argument must be an instance of Stopwatch. But when debug mode is off, there's no Stopwatch to be passed as an argument, instead it passes null. And because of $stopwatch strictly declared as an instance of Stopwatch we got an exception (Argument 2 passed to Gordalina\MixpanelBundle\Mixpanel\Flusher::__construct() must be an instance of Symfony\Component\Stopwatch\Stopwatch, null given)

Can you please fix it by making $stopwatch not required. Thanks a lot!

**Comment by gordalina** [comment]
Fixed in 2.6.2.2

**Comment by gordalina** [comment]
Can you test to see if its working as it should?

**Comment by kpotehin** [comment]
Fixed! Thank you sir!
