### ISSUE TITLE
I'm struggling to update Mixpanel via the bundle

### ISSUE THREAD

**Issue by sterichards** [gordalina/GordalinaMixpanelBundle#3]
Hi,

I've installed the bundle, registered it and included it within a Doctrine event listener. All the values in the examples seem to be defined within annotations. How is it possible for me to pass data values to be processed. IE - I want to pass a mixpanel user ID to a function and have the bundle update Mixpanel based upon that mixpanel user ID

Regards,

**Comment by gordalina** [comment]
You can get the manager registry service `gordalina_mixpanel.registry`, get mixpanel project, and set the user directly.

``` php
$registry = $container->get('gordalina_mixpanel.registry');
$mixpanel = $registry->getProject('default');
$mixpanel->people->set($userId, $props);
```
