### ISSUE TITLE
`getUserProperties()` returns null instead of array if instance of user is a doctrine proxy

### ISSUE THREAD

**Issue by nesl247** [gordalina/GordalinaMixpanelBundle#31]
Whenever `getUserProperties()` is called, and the instance happens to be a Doctrine proxy object, the `get_class()` comparison fails, and returns null instead of array.

https://github.com/gordalina/GordalinaMixpanelBundle/blob/e4aea20783774ada032dfa3fe15276f5cda66f99/Mixpanel/EventListener/MixpanelListener.php#L97

https://github.com/gordalina/GordalinaMixpanelBundle/blob/master/Mixpanel/Security/UserData.php#L101-L110

**Comment by gordalina** [comment]
~Fixed by #32~

**Comment by gordalina** [comment]
@RomulusED69 do you have any ideas on how to solve this?

**Comment by Kocal** [comment]
In this specific case, you can get the real class behind the Doctrine proxy by using [`ClassUtil::getRealClass`](https://github.com/doctrine/common/blob/3.4.x/src/Util/ClassUtils.php#L32-L42) or [`ClassUtil::getClass`](https://github.com/doctrine/common/blob/3.4.x/src/Util/ClassUtils.php#L55-L58).

But I think you can use [`is_a`](https://www.php.net/manual/fr/function.is-a.php) instead for a more generic way.

**Comment by gordalina** [comment]
Fixed by #33, released in `v5.0.2`
