### ISSUE TITLE
Don't send `DateTimeInterface` as value for properties in `extra_data`

### ISSUE THREAD

**Issue by nesl247** [gordalina/GordalinaMixpanelBundle#34]
When a user is updated, if the property's value would be a `DateTimeInterface`, it should be formatted as a string, rather than being sent as an object.

Original:
![CleanShot 2023-01-23 at 13 13 41](https://user-images.githubusercontent.com/1037526/214117625-13c9c070-6993-44f0-8b77-8c33e55180c0.png)

Formatted:
![CleanShot 2023-01-23 at 13 08 45](https://user-images.githubusercontent.com/1037526/214117621-4b0a1334-83cd-4119-a84b-c0ec4cd6c8dd.png)

```--- /dev/null
+++ ../Mixpanel/Security/UserData.php
@@ -123,7 +123,13 @@
 
                 foreach ($prop as $element) {
                     try {
-                        $this->properties[$className][$element['key']] = $this->accessor->getValue($instance, $element['value']);
+                        $value = $this->accessor->getValue($instance, $element['value']);
+
+                        if ($value instanceof \DateTimeInterface) {
+                            $value = $value->format(DATE_ATOM);
+                        }
+
+                        $this->properties[$className][$element['key']] = $value;
                     } catch (\Exception $e) {
                         if ($this->displayErrors) {
                             throw $e;
```

**Comment by nesl247** [comment]
I haven't submitted a PR as I want to know if you are good with this change first.

**Comment by gordalina** [comment]
This is great, please submit a PR with tests and I'll get it merged in. Thank you!
