### ISSUE TITLE
ReflectionException in Flusher.php

### ISSUE THREAD

**Issue by walva** [gordalina/GordalinaMixpanelBundle#4]
Hello,

I tried to install your bundle in my project but it fails. I got a ReflectionException. Here is the stack trace : 

```
in Flusher.php line 137
at ReflectionClass->getProperty('_events') in Flusher.php line 137
at Flusher->getQueue(object(Mixpanel_000000004482c3c300000000f1d660c5788208729a42c03591129b1a96c81cd9), '_events', false) in Flusher.php line 110
at Flusher->dataCollectorFlush() in Flusher.php line 64
at Flusher->flush() in appDevDebugProjectContainer.php line 10630
at GordalinaMixpanelBundleMixpanelFlusher_000000004482c3ff00000000f1d660c5788208729a42c03591129b1a96c81cd9->flush() in FinishRequestListener.php line 38
at FinishRequestListener->onFinishRequest(object(FinishRequestEvent)) in appDevDebugProjectContainer.php line 9580
```

My configuration is : 

```
gordalina_mixpanel:
#    enable_profiler: %kernel.debug%
    projects:
        default:
            token: PROVIDED BY MIXPANEL
```

I'm using WAMP with PHP 5.5. 
Here is my composer : 
"php": ">=5.3.3",
        "symfony/symfony": "~2.8",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "stof/doctrine-extensions-bundle": "~1.1",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0",
        "sensio/framework-extra-bundle": "~3.0",
        "incenteev/composer-parameter-handler": "~2.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "jms/di-extra-bundle": "~1.7",
        "cocur/slugify": "~0.10.2",
        "friendsofsymfony/rest-bundle": "~1.7",
        "jms/serializer-bundle": "~1.0",
        "nelmio/api-doc-bundle": "~2.8",
        "nelmio/cors-bundle": "~1.4",
        "jms/translation-bundle": "~1.1",
        "jms/i18n-routing-bundle": "~1.1",
        "coresphere/console-bundle": "dev-master",
        "lexik/translation-bundle": "~4.0",
        "sonata-project/intl-bundle": "~2.2",
        "hwi/oauth-bundle": "*",
        "cometcult/braintree-bundle": "~0.1.0",
        "symfony/debug": "~2.8.0",
        "symfony/var-dumper": "~2.8.1",
        "symfony/http-kernel": "~2.8.0",
        "ali/datatable": "~2.1",
        "friendsofsymfony/comment-bundle": "^2.0",
        "doctrine/doctrine-migrations-bundle": "^1.0",
        "gordalina/mixpanel-bundle": "dev-master"

It happen also with bundle ~2.6. I tried to change private $_events; to public in class "Mixpanel extends Base_MixpanelBase". After that it work.

If I do that, I have an other problem which will be described in a second issue.

Good luck anyway, your bundle seems to be very powerfull!

**Comment by nicholasruunu** [comment]
The problem is the lazy loadings here:
https://github.com/gordalina/GordalinaMixpanelBundle/pull/6/commits/d2a01400a8d3ffa277856c94e331aac78e7eb967#diff-27d5fb3d463c1ab5c70c72300a7851faL83

Since the `$_event` property won't exist on the proxy object it causes problems.

**Comment by gordalina** [comment]
This support symfony 4 & 5 now
