### ISSUE TITLE
Add Condition in Annotations

### ISSUE THREAD

**Issue by RomulusED69** [gordalina/GordalinaMixpanelBundle#9]
## Objective

Add condition in annotation in order to filter events

## Why
In submit form, maybe you want dissociate display edit form and submit form but action is same in all cases.

## Example
```php
    /**
     * @Mixpanel\Track("Your event", condition="request.getMethod() in ['GET']")
     */
    public function yourAction()
    {
        // ...
    }
```

**Comment by gordalina** [comment]
Closed by #10
